### ISSUE TITLE
WebExtension

### ISSUE THREAD

**Issue by IzzySoft** [piroor/secondsearch#18]
Are you planning to port this to a web extension, so it remains working with FF57+? Would be a shame to miss one of my favorite addons.

**Comment by piroor** [comment]
Second Search has two main features: "one time search" and "treat bookmark keywords as search engines". One time search is now implemented as "one-off search" by Firefox itself, so I think this addon maybe obsolete. Instead of migration, I think I should work for something to convert bookmark keywords to genuine search engines (then they will be avialable on Firefox's built-in one-off search.)

**Comment by IzzySoft** [comment]
Thanks for your fast response, @piroor – but though FF has that part covered "somehow" for several versions now, I'm not sure it compares. With Second Search, I start typing a term into the search box, then use the cursor keys to navigate search terms as well as engines. And I have the "add site-X" whenever a search definition was detected. Is all that really covered by Firefox itself meanwhile? I only noticed that, with FF55, the one-off buttons also appear when using the address bar. But it's much harder to navigate than I'm used from SecondSearch. Might be a "getting used to", though – I just now discovered how to use that with keyboard-only as well. Hard to tell which parts SecondSearch might provide there :wink: Have to try that on my test machine with SecondSearch disabled tomorrow or on the weekend.

Btw: If you're looking for another missing addon: [Server Switcher](https://addons.mozilla.org/de/firefox/addon/server-switcher/) was abandoned, it seems. Someone started a comparable WebExtension with [Domainswitcher](https://github.com/peterbe/domainswitcher) over a year ago but seems to have given up. It would just need a few minor adjustments to be usable (it's currently fixed to 3 domains as the author didn't know how to set up a config page). In case you fork that and fix the gap, please let me know :stuck_out_tongue_winking_eye:

**Comment by piroor** [comment]
Now, WE version Second Search is under development.
http://piro.sakura.ne.jp/xul/xpi/nightly/secondsearch-we.xpi

 * Never work around Firefox's built in search bar, instead this introduce new search button and its custom search box.
 * Regular search engines won't be listed, because there is no WebExtensions API to read them.
 * Only bookmarks including `%s` in its URL are listed as fake search engines.
 * Drag and drop is not supported because there is no WebExtensions API to accept drag and drop onto custom toolbar button.
 * No configuration dialog yet.
 * No static listing mode yet.

**Comment by piroor** [comment]
I've released 2.0.0.
